name: ping streamlit app 

on:
  schedule:
    - cron: '*/10 * * * *' # run every 10 mins 

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    steps:
      - name: ping render app
        run: curl https://convnn-mnist.onrender.com/
